WIFI_SSID="<SSID>"
WIFI_PASS="<PASS>"

AIO_USER="Tapgate"
AIO_KEY="aio_SVVQ61HhuAzANAn0gjaTixoF0KMy"
BROKER="io.adafruit.com"
PORT=1883

CARD_KEY_A="KeyA"
CARD_KEY_B="KeyB"
CARD_PASS_BLOCK=16
CARD_BITS="8,119,143,255"

API_KEY="Pr0duct!onCol13ct!0nWr17tenDen!ed!$r@el"